### ISSUE TITLE
global  reconnect / retry mechanism

### ISSUE THREAD

**Issue by RobinKamps** [ngx-grpc/ngx-grpc#42]
Hi Semen,

is there a feature, wich allows global reconnects / retries for server side streams?
the basic reconnect, i am implementing is getting a bit tedious:
- every stream subscription is assigned to an attribute.
- on completed an unsubscribe and a re-subscribe is performed.
- of course on network issues there should be a callback/test to navigator isonline or something like timeouts so that the reconnect is only triggered if the device is online again or can ping the backend etc.
this manual approch works fine, but it would be great if there is a way to configure / use a global reconnect/retry mechanism.

Thank you very much!

**Comment by smnbbrv** [comment]
Hi @RobinKamps ,

there is no built-in feature, but it is kinda built-in feature of the rxjs.

This is an example of what I normally use (not globally, just in place):

```ts
    this.client.listen(new MyRequest())
        .pipe(
          // infinitely retry in 3 seconds in case of error
          retryWhen(errors => errors.pipe(
            tap(() => this.status = null),
            delay(3000),
          )),
        )
        .subscribe(() => /* here is your logic */);
```

If you need this to be enabled globally, just transform this code into an interceptor. Note, that interceptor's observables do not throw errors, so you might need some step before which looks for particular status codes and transforms them into errors. This is actually way more flexible approach because you can also limit reconnection to the specific status codes, e.g. to reconnect only on networking issues.

Please keep in mind that having global interceptor is good for most of the cases, but it will also make it problematic to switch it off for the particular requests. It might be more comfortable in the beginning but some day you might regret it.

**Comment by RobinKamps** [comment]
Thank you very much.
i already tried the retryWhen operator, but could not get it to work to reconnect on completed for streams.
Your hint about transforming into errors (e.g. throwError), so that retryWith can pick it up, was helpful.
Now its working as expected.
