### ISSUE TITLE
Generate GrpcMessagePool

### ISSUE THREAD

**Issue by stocksr** [ngx-grpc/ngx-grpc#73]
I have setup Logging as suggested and all was working well, until I used the "Any" type

I found this comment in the logging setup - which solved my problem
`  // please beware: if you use google.protobuf.Any you must pass the proper `messagePool` argument` 

Would it be possible for there to be a generated array of all the messages types suitable for creating a MessagePool to pass to the logger?

**Comment by smnbbrv** [comment]
Hi, 

Of course. The only problem here (and why this pool is relevant at all) is that the bigger this pool is, the bigger is the initial data chunk that the browser must download before the application gets interactive. This is the difference to the server side grpc client - there is no data limits on the server. If this is not bothering you, e.g. the system you implement does not have network limitations etc you can just pass all your messages in

**Comment by stocksr** [comment]
As my app is bundled by the angular compiler, I assume that any additional generated items will be excluded from the bundle unless actually used,  in my use case I have about 61 message types (and that is growing as we add more features to the system)  that could be passed in the same Any field, so I was hoping that I would not have to list the message types by hand in the debug code.

I am happy to attempt to add a generated GrpcMessagePool to this project - however before I start 
1. Would the change be accepted?
2. Would it be better as a new (optionally) generated file or tacked on to the end of an existing file?

**Comment by stocksr** [comment]
ok - actually I have worked out I can use the typescript compiler to do this.
```
import * as CommandMessages from '../../../generated/command.generated.pb';
const pool = new GrpcMessagePool([...Object.values(CommandMessages)]);
```
Should I add this to the readme?

**Comment by smnbbrv** [comment]
> I assume that any additional generated items will be excluded from the bundle unless actually used

This is not true. The process is the following:

- Message is received
- The message has `Any` message field
- In order to decode it one needs the protobuf message implementation, so it needs to be loaded
- To load the message, you need to actually need to import this file
- Since the file is imported and the imported token (message) is used e.g. in `switch`-`case` or in `if` statement, **it will be embedded in the chunk**

> `const pool = new GrpcMessagePool([...Object.values(CommandMessages)]);`

This will work for root-level messages only. This also will include e.g. enums

> Would the change be accepted?

No, because this is an anti-pattern. When you have `Any` field type, it is most of the time clear which messages are exactly used.

For the particular problem you are trying to solve: as I understand, for just debugging purposes you want to have the pool for the `Any` fields. You can try either (or a combination) of the following:

- put your pools in the environment.ts files, that in production you don't have the pool at all
-  use dynamic es6 imports (`e.g. const pool = import( '../../../generated/command.generated.pb')`. This will be lazily load (but still it will load **the whole module**)

**Comment by stocksr** [comment]
Thank you for your explanations, they are very helpful.

"veeeery specific business needs"   < I think this is a key point here so I will use the solution I have identified and this issue can be closed,.

For the benefit of anybody else reading this issue in the future my specific use case is

On my server side I have an existing mediator implementation where I have a CommandDispatcher class that dispatches commands to the relevant implementation class.  - I am attempting to add a grpc interface to allow the UI project to directly dispatch commands; to do this I have created a message for each of my existing commands, and in my client code I have a similar dispatcher service that wraps the grpc service and sends the command classes to the backend.

I did consider having a rpc method per command but the server side implementation of each of those methods was identical, so a generic one using a wrapper message with an Any property seemed more logical.

All my command messages are top level messages and are defined in the same proto file, and are the only things in that file, so I guess that is what makes my solution work.

"because protobuf is out there to add strong typing" < Agreed and I am already appreciating the strongly typed command classes, is there a better proto native approach to what I am doing that I am not aware of?

Regarding bundle size - All these messages will be sent by my UI to the server in some situation, so including them all in the bundle is not a big issue for me.
