### ISSUE TITLE
Strict mode: goole.protobuf.Empty or message without fields are not supported

### ISSUE THREAD

**Issue by treebeardcpu** [ngx-grpc/ngx-grpc#9]
With something like this:
```
service HelloService {
  rpc SayHello (google.protobuf.Empty) returns (SayHelloReply);
}

message SayHelloReply {
  string message = 1;
}
```
will result in an error `Empty` is not a constructor`

**Another case**:

```
service HelloService {
  rpc SayHello (SayHelloRequest) returns (SayHelloReply);
}

message SayHelloRequest {};
message SayHelloReply {
  string message = 1;
}
```
will result in an error `SayHelloRequest` is not a constructor`

I tried an empty reply as well and there are other errors.
Some of the services that I'm dealing with use Empty because they don't need any fields.

Absorbing #8 into this one.

**Comment by smnbbrv** [comment]
Hi @treebeardcpu 

I use `google.protobuf.Empty` really a lot in all my projects and haven't experienced issues yet

Could you provide an example where you get the errors like  `Empty` / `SayHelloRequest is not a constructor`? I mean this happens in your TypeScript code I guess?

**Comment by treebeardcpu** [comment]
The `is not a consturctor ` error I was getting in the web console... I'll check that service again later this week.

**I do have TS strict mode on**, which gets me the error `declared but never read` in the [three places mentioned in #8](https://github.com/ngx-grpc/ngx-grpc/issues/8#issue-623751254).
A fourth place I forgot to mention is in `sayhello.pb.ts` in the import.
The `import * as googleProtobuf000 from '../google/protobuf/empty.pb'` will have `declared but never read`.

**Is it possible to be strict-compliant for the generations?**

Just to clarify how I'm using `Empty`:
In my `.proto` file, I'm importing `Empty` using `import "google/protobuf/empty.proto";`
The `empty.proto` is picked up from when I put it in `/usr/local/include`.

`empty.pb.ts` is generated by `protoc` and I'm using that generated `Empty` class in my service clients.

Is this the way that you're using `Empty`?

**And would it be better if types like `google.protobuf.Empty` and `google.protobuf.Timestamp` had built-in support in the `ngx-grpc` package?** Other languages besides JS/TS have them in their official `protobuf` package, so I think it is within scope. I don't think `grpc-web` has something similar. This would be great for this Angular-native project. It also wouldn't have to get re-generated on `protoc` runs.

I'm not talking about [well-known types](https://github.com/googleapis/googleapis/tree/master/google/type) (although that would be awesome for Angular users too, it might belong in a separate add-on project?)

Thanks for this project by the way!

**Comment by smnbbrv** [comment]
Hi again, sorry for delay. 

Theoretically it is possible to support strict mode; however there is no target to do it in the nearest future. Here is a universal workaround I would propose for such problems: you can generate a separate angular library and put all grpc communication in there. Since it will be built in a separate project you can use the strict mode and any sort of validation / compiler options on a primary one and other settings on the lib.

The project does not have a special lib for well-known types because, well, it is an additional effort to support one more package, which is transient: for every newer version of the generator it would require another version of the package. Meanwhile, now they are just generated with current version of the installed compiler, which is very comfortable to the end user because he simply cannot have the libs mismatch.

**Comment by smnbbrv** [comment]
By the way, could you please provide the relevant sections of your tsconfig.json files? The packages are tested with strict mode on, https://github.com/ngx-grpc/protoc-gen-ng/blob/656ed897735d175165d91894e93748cf492916e3/test/tsconfig.json#L12 , which means it should be already supported...
